# This is a copy of mnist_valid.yaml with modified parameters
# in order to make the tests in DEBUG_MODE faster

!obj:pylearn2.train.Train {
    dataset: &train !obj:pylearn2.datasets.mnist.MNIST {
        which_set: "train",
        shuffle: 0,
        start: 0,
        stop: 100
    },
    model: !obj:pylearn2.models.mlp.MLP {
        batch_size : 1,
        nvis: 784,
        layers: [
            !obj:pylearn2.models.mlp.RectifiedLinear {
                max_col_norm: 4.378017,
                dim: 1,
                irange: 0.00891030471479,
                layer_name: 'h0',
                init_bias: 0.000000
            },
            !obj:pylearn2.models.mlp.RectifiedLinear {
                max_col_norm: 2.970242,
                dim: 1,
                irange: 0.0575059125935,
                layer_name: 'h1',
                init_bias: 0.000000
            },
            !obj:pylearn2.models.mlp.Softmax {
                max_col_norm: 4.626974,
                sparse_init: 0,
                layer_name: 'y',
                n_classes: 10
            }
        ]
    },
    algorithm: !obj:pylearn2.training_algorithms.sgd.SGD {
        monitoring_dataset : {
            valid: !obj:pylearn2.datasets.mnist.MNIST {
                which_set: "train",
                shuffle: 0,
                start: 100,
                stop: 200
            },
        },
        learning_rate: 0.097259,
        learning_rule: !obj:pylearn2.training_algorithms.learning_rule.Momentum {
            init_momentum: 0.5
        },
        cost: !obj:pylearn2.costs.mlp.dropout.Dropout {
             input_include_probs: { 'h0' : .8 },
             input_scales: { 'h0' : 1.25 }
        },
        termination_criterion: !obj:pylearn2.termination_criteria.MonitorBased {
            channel_name: "valid_y_misclass",
            N: 1,
            prop_decrease: 0.
        }
    },
    extensions: [
        !obj:pylearn2.train_extensions.best_params.MonitorBasedSaveBest {
            channel_name: "valid_y_misclass",
            save_path: "${PYLEARN2_TRAIN_FILE_FULL_STEM}_best.pkl"
        },
        !obj:pylearn2.training_algorithms.learning_rule.MomentumAdjustor {
            start: 1,
            saturate: 698,
            final_momentum: 0.699217
        },
        !obj:pylearn2.training_algorithms.sgd.LinearDecayOverEpoch {
            start: 1,
            saturate: 560,
            decay_factor: 0.022292
        }
    ],
    save_path: "${PYLEARN2_TRAIN_FILE_FULL_STEM}.pkl",
    save_freq : 1
}
